M48
; DRILL file {KiCad 8.0.3} date 2024-06-23T17:05:02+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-06-23T17:05:02+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0925
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X4.6063Y-3.3071
X4.9665Y-3.3071
T2
X4.0354Y-3.0512
M30
